### ISSUE TITLE
README

### ISSUE THREAD

**Issue by jbutz** [etsy/deployinator#36]
It looks like the readme section for "Customizing your stack" might be wrong. It doesn't do anything for me.

**Comment by jayson** [comment]
@jbutz We just released a gem version of this (soon to be on rubygems). I have verified that it works in the new version (check the master, not the master_old branch). If not what were you doing that wasn't working in the old version? I know this is years later but figured you might want to use the new release

**Comment by jbutz** [comment]
Thanks, looks good
