### ISSUE TITLE
Exception during the deploy

### ISSUE THREAD

**Issue by inigomedina** [etsy/deployinator#45]
Hi,

I've tried Deployinator still on dev environment, following the Readme. Everything looks fine, and it runs well with the sample configuration by default. But when I start to add the code you give for config/base.rb, stacks/test_stack.rb, helpers/test_stack.rb, the push-deploy action always ends in an error: **There was an exception during this deploy. Aborted! (undefined method `[]' for nil:NilClass)**.

Do you think is anything related to environment (my linux distro, etc.)? Related to the tailer? ¿?

Thanks in advance. ;)

**Comment by inigomedina** [comment]
I've been looking the log again. It looks like Deployinator's Helpers are not loaded, and then it throws an exception when I call to any of those methods.

Ideas?

**Comment by inigomedina** [comment]
I found the problem, tracing it. In the meanwhile I've found other issues, all of them related to dependencies-stack of deployinator-tailer.rb.

I keep playing and discovering more issues. Just for fun. ;)

**Comment by xyxu** [comment]
i had the same problem, ruby-2.1.2

**Comment by jayson** [comment]
@inigomedina nigomedina What was the problem with this that you fixed? I'm not seeing it on my environment but others are starting too.
